-- Migration: Add missing client fields
-- Run this on an existing database to add the new columns

ALTER TABLE clients ADD COLUMN IF NOT EXISTS forma_giuridica VARCHAR(100);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS obsoleto BOOLEAN DEFAULT FALSE;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS contributo VARCHAR(50);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS pagamento VARCHAR(255);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS codice_iva VARCHAR(100);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS split_payment BOOLEAN DEFAULT FALSE;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS conto VARCHAR(255);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS listino VARCHAR(255);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS banca VARCHAR(255);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS iban VARCHAR(50);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS swift VARCHAR(20);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS pec_fe VARCHAR(255);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS estero BOOLEAN DEFAULT FALSE;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS lingua VARCHAR(50) DEFAULT 'Italiano';
ALTER TABLE clients ADD COLUMN IF NOT EXISTS indirizzo_numero VARCHAR(20);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS sede_tipo VARCHAR(50);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS sede_principale BOOLEAN DEFAULT TRUE;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS telefono_2 VARCHAR(50);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS telefono_3 VARCHAR(50);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS email_pec VARCHAR(255);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS indirizzo_web VARCHAR(255);
